name: CD - Build and Deploy

on:
  push:
    branches:
      - cd-cyrus


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK for Spring Boot
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      # Build backend
      - name: Build backend with Maven
        run: |
          cd rbs-backend
          mvn clean package -DskipTests

      # Set up Node.js/Bun for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install Bun
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Set up PATH to include Bun
      - name: Set up PATH for Bun
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Build frontend with debug output
      - name: Build frontend
        run: |
            cd rbs-frontend
            bun install
            API_BASE_URL="http://${{ secrets.DROPLET_HOST }}" bun run build
            # Debug: Verify .output directory exists
            ls -la .output/
            echo "Contents of .output directory:"
            find .output -type f | head -n 5

      # Create deployment package
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp rbs-backend/target/*.jar deploy/rbs-backend.jar
          
          # Create proper structure for Nuxt
          mkdir -p deploy/frontend
          
          # Copy the entire .output directory structure
          cp -r rbs-frontend/.output deploy/frontend/
          
          # Debug: Verify the structure in the deployment package
          ls -la deploy/frontend/
          ls -la deploy/frontend/.output/
          
          # Create package.json for production dependencies
          echo '{
            "name": "rbs-frontend",
            "dependencies": {
              "defu": "^6.1.2"
            }
          }' > deploy/frontend/package.json

          # Create run scripts
          echo '#!/bin/bash
          cd /opt/rbs
          nohup java -jar rbs-backend.jar --spring.profiles.active=prod > backend.log 2>&1 &
          echo $! > backend.pid' > deploy/start-backend.sh

          echo '#!/bin/bash
          cd /opt/rbs
          if [ -f backend.pid ]; then
            kill $(cat backend.pid)
            rm backend.pid
          fi' > deploy/stop-backend.sh

          echo '#!/bin/bash
          cd /opt/rbs/frontend
          # Install production dependencies for Nuxt
          npm install --omit=dev
          # Print directory structure for debugging
          echo "Directory structure before starting:"
          ls -la
          ls -la .output/ || echo ".output directory not found!"
          # Start the Nuxt server
          nohup node .output/server/index.mjs > frontend.log 2>&1 &
          echo $! > frontend.pid' > deploy/start-frontend.sh

          echo '#!/bin/bash
          cd /opt/rbs
          if [ -f frontend/frontend.pid ]; then
            kill $(cat frontend/frontend.pid)
            rm frontend/frontend.pid
          fi' > deploy/stop-frontend.sh

          chmod +x deploy/*.sh

      # Deploy to DigitalOcean with explicit file mode preservation
      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "/tmp/rbs-deploy"
          strip_components: 1
          overwrite: true
          # Preserve file mode to ensure executable scripts work properly
          rm: true

      # Run deployment script on server with more debugging
      - name: Execute deployment commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop existing services
            if [ -f /opt/rbs/stop-backend.sh ]; then
              cd /opt/rbs && ./stop-backend.sh
            fi
            if [ -f /opt/rbs/stop-frontend.sh ]; then
              cd /opt/rbs && ./stop-frontend.sh
            fi

            # Create deployment directory if it doesn't exist
            mkdir -p /opt/rbs

            # Clean up old frontend files to ensure complete replacement
            echo "Removing old frontend directory..."
            rm -rf /opt/rbs/frontend
            mkdir -p /opt/rbs/frontend

            # Debug: Check what's in the temp directory
            echo "Contents of /tmp/rbs-deploy:"
            ls -la /tmp/rbs-deploy/
            echo "Contents of /tmp/rbs-deploy/frontend:"
            ls -la /tmp/rbs-deploy/frontend/
            
            # Copy deployment files with verbose output
            echo "Copying backend JAR..."
            cp -v /tmp/rbs-deploy/rbs-backend.jar /opt/rbs/
            
            echo "Copying frontend files..."
            cp -rv /tmp/rbs-deploy/frontend/* /opt/rbs/frontend/
            
            echo "Copying scripts..."
            cp -v /tmp/rbs-deploy/*.sh /opt/rbs/
            chmod +x /opt/rbs/*.sh

            # Debug: Check if .output directory exists in source and destination
            echo "Source .output directory:"
            ls -la /tmp/rbs-deploy/frontend/.output/ || echo "Source .output directory missing!"
            
            echo "Destination .output directory:"
            ls -la /opt/rbs/frontend/.output/ || echo "Destination .output directory missing!"
            
            # If .output directory isn't copying correctly, try direct copy
            if [ ! -d "/opt/rbs/frontend/.output" ] && [ -d "/tmp/rbs-deploy/frontend/.output" ]; then
              echo "Direct copy of .output directory..."
              mkdir -p /opt/rbs/frontend/.output
              cp -rv /tmp/rbs-deploy/frontend/.output/* /opt/rbs/frontend/.output/
            fi

            # Final verification of deployed structure
            echo "Final structure of frontend directory:"
            ls -la /opt/rbs/frontend/
            if [ -d "/opt/rbs/frontend/.output" ]; then
              ls -la /opt/rbs/frontend/.output/
              echo "Server directory:"
              ls -la /opt/rbs/frontend/.output/server/ || echo "Server directory missing!"
            else
              echo ".output directory still missing!"
            fi

            # Start services
            echo "Starting backend..."
            cd /opt/rbs && ./start-backend.sh
            echo "Starting frontend..."
            cd /opt/rbs && ./start-frontend.sh

            # Clean up
            rm -rf /tmp/rbs-deploy