name: Java Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    name: Run Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install dependencies
        run: mvn -f ./rbs-backend/pom.xml install

      - name: Run Checkstyle
        run: mvn -f ./rbs-backend/pom.xml checkstyle:check

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: ./rbs-backend/target/checkstyle-result.xml

  pmd:
    name: Run PMD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven  # Install Maven

      - name: Run PMD
        run: mvn -f ./rbs-backend/pom.xml pmd:check

      - name: Upload PMD report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: ./rbs-backend/target/pmd.xml
